
/**************************************************************
 *	
 *	bossTheme, 8 bit, 11025Hz,
 *	1 channel, 539712 bytes/channel
 *	Total Size: 1 * 539712 + 4 (header) = 539756 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\bench\Documents\School\GT\Spring2020\CS2261\Project\bossTheme.wav
 *	Time-stamp: Sat Apr 18 02:45:15 2020
 *	
 **************************************************************/

#ifndef __BOSSTHEMEH__
#define __BOSSTHEMEH__

#define BOSSTHEMEFREQ 11025
#define BOSSTHEMELEN 539712

extern const unsigned char bossTheme[539712];

#endif /* __BOSSTHEMEH__ */
