
/**************************************************************
 *	
 *	gunSound, 8 bit, 11025Hz,
 *	1 channel, 10727 bytes/channel
 *	Total Size: 1 * 10727 + 4 (header) = 10771 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\bench\Documents\School\GT\Spring2020\CS2261\Project\gunSound.wav
 *	Time-stamp: Fri Apr 17 19:46:51 2020
 *	
 **************************************************************/

#ifndef __GUNSOUNDH__
#define __GUNSOUNDH__

#define GUNSOUNDFREQ 11025
#define GUNSOUNDLEN 10727

extern const unsigned char gunSound[10727];

#endif /* __GUNSOUNDH__ */
