
/**************************************************************
 *	
 *	gunSound, 8 bit, 11025Hz,
 *	1 channel, 3968 bytes/channel
 *	Total Size: 1 * 3968 + 4 (header) = 4012 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\bench\Documents\School\GT\Spring2020\CS2261\Project\gunSound.wav
 *	Time-stamp: Sat Apr 18 02:41:04 2020
 *	
 **************************************************************/

#ifndef __GUNSOUNDH__
#define __GUNSOUNDH__

#define GUNSOUNDFREQ 11025
#define GUNSOUNDLEN 3968

extern const unsigned char gunSound[3968];

#endif /* __GUNSOUNDH__ */
